#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=22 color=0xbf272822 blur_radius=20

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=4
  padding_right=4
  icon.font="SF Pro:Semibold:13.0"
  label.font="SF Pro:Semibold:13.0"
  icon.color=0xffe6db74
  label.color=0xffe6db74
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

# -- Middle Side Items --
source $ITEM_DIR/calendar.sh

# -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Items --
source $ITEM_DIR/battery.sh
source $ITEM_DIR/net.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/input_source.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/ram.sh
source $ITEM_DIR/media.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
